S3_ACCESS_KEY: 'AKIAJZM2LPMTWLK7PWHA'
S3_SECRET_KEY: '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'

FB_ACCES_KEY: '445360272621130'
FB_SECRET_KEY: 'b1e4e9fbc2e8397bd440a1de26956dea'

TW_ACCES_KEY: 'A7fne14l6NAvX8fqRbTTbRGXe'
TW_SECRET_KEY: 'ylkHeBq3ImpP6yfiPkY8pL0j9PFCihzKXVtZpO0wp4zvZYnuJ3'